use_frameworks!
inhibit_all_warnings!

target 'OLNetwork_Example' do
  pod 'OLNetwork', :path => '../'

  target 'OLNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
